# Generated by Django 5.1.4 on 2024-12-15 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionLot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_time', models.DateTimeField(default=datetime.datetime(2024, 12, 22, 9, 19, 28, 599056, tzinfo=datetime.timezone.utc))),
                ('images', models.ImageField(default=None, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
