# Generated by Django 5.1.4 on 2025-03-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlot',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
