# Generated by Django 5.1.4 on 2025-01-18 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlot',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourite_lots', to=settings.AUTH_USER_MODEL),
        ),
    ]
