# Generated by Django 5.1.4 on 2025-03-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='viber',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
